# Generated by Django 5.0.6 on 2024-06-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
            ],
        ),
    ]
