# Generated by Django 5.0.6 on 2024-06-19 01:20

import encrypt_decrypt_fields.orm.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_spotifyprofile_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyprofile',
            name='display_name',
            field=encrypt_decrypt_fields.orm.django_fields.EncryptedBinaryField(verbose_name=models.CharField(max_length=255)),
        ),
    ]
