# Generated by Django 5.0.6 on 2024-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_spotifyprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyprofile',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
    ]
